README.md, templates/statefulset.yaml, values.yaml
Ability to add secrets to the pod for example add keystore as secret for kafka ssl
=> Add secrets

README.md
=> Extending Readme.md with Installation Instructions (issues 20 and 23)

templates/service.yaml
Issue #25 Bug fix 
- fixes #25 
=> loadBalancerSourceRanges typo in template service.yaml

Chart.yaml, templates/statefulset.yaml, values.yaml
Adds support of custom ConfigMaps, which is similar to custom Secrets idea.
One of the example is to be able to mount a ConfigMap containing Kerberos configuration file for Nifi.
- fixes #48 
=> add custom configmaps suport

Chart.yaml, README.md, configs/flow.xml, templates/_helpers.tpl, templates/statefulset.yaml, values.yaml
=> Add nifi registry support

Chart.yaml
The PR fixes a spelling mistake in the alias of the nifi-registry dependency.
- fixes #
Because of the mistake, when you try to inject the overriden values to the subchart, they never apply.
Example of a `values.yaml` that would actually override the subchart values while respecting the spelling mistake.
```
regitsry:
enabled: true
url: ""
port: 80
replicaCount: 2
```
=> Fix spelling mistake in the alias name of the nifi-registry dependency.

.gitignore, Chart.yaml, README.md, charts/ca/.helmignore, charts/ca/Chart.yaml, charts/ca/templates/NOTES.txt, charts/ca/templates/_helpers.tpl, charts/ca/templates/deployment.yaml, charts/ca/templates/service.yaml, charts/ca/templates/volume.yaml, charts/ca/values.yaml, configs/authorizers.xml, configs/nifi.properties, templates/_helpers.tpl, templates/service.yaml, templates/statefulset.yaml, values.yaml
Add TLS support to the chart....heavily based on example/knowledge from https://github.com/sushilkm/nifi-chart.git.  This is likely a very rough first draft but seems to work for me.
- fixes #
=> Add TLS support

templates/statefulset.yaml
This PR just removes an extra prop replace since it is being done in a new IF block below. Plus I removed some superfluous whitespace and corrected a spelling.
- fixes #
I am not bumping the version for this as I dont think it is necessary. I think it can wait for the next release.
=> Remove extra prop

charts/ca/templates/deployment.yaml, charts/ca/values.yaml
This PR adds a security context to the CA chart deployment. This is necessary for people that have PSP setup in certain ways.
- fixes # NA
I didn't increment chart number since I feel like this could be rolled into the next release.
=> Add security context

README.md
`--name` has been deprecated in Helm 3
=> Update documentation for Helm 3

templates/statefulset.yaml
There are a lot of other places in the templates where the https vs http conditionals are done so that the https port takes precedent (see https://github.com/cetic/helm-nifi/blob/master/templates/statefulset.yaml#L308-L312). I would like that to be the case here as well as it will allow this chart to be used as a subchart of an umbrella chart and not have both http and https ports be present in the created yaml. There is no way for an umbrella chart to set a charts default variable to null resulting in `{{- if .Values.properties.httpPort }}` always returning true. 
- fixes #
=> Change port if statements

templates/statefulset.yaml
This was commented out in #76 , but is needed for proper flow bootstrapping and out-of-the-box nifi-registry support
- fixes #
=> Re-enable flow.xml bootstrapping

charts/ca/values.yaml
Same as the base chart's nifi version.
- fixes #
=> Update the ca chart's nifi-toolkit image to v1.12.1

README.md
Added documentation example for custom libs usage, and did some cleanup of the readme.
=> Custom libs documentation

Chart.yaml
Signed-off-by: Rogier Dikkes <1867776+a-nldisr@users.noreply.github.com>
Raised version of nifi-registry helm chart to 0.3.0, this will enable registry version 0.8.0 to be used. This implements new PostgresQL version support, OIDC and some bug fixes with flow versions. 
=> Raised nifi-registry helm chart version to 0.3.0

Chart.yaml, templates/statefulset.yaml
When HostNetwork is used this PR will bind the FQDN to `0.0.0.0` instead of the hostname (which might not resolve or point to localhost).
No issue, but I can open one if needed.
@banzo 
@AyadiAmen 
@alexnuttinck 
=> Hostnet fix

Chart.yaml
Signed-off-by: Martijn Kint <tunaman@gmail.com>
Raised version of nifi-registry helm chart to `0.3.2` this will enable extra environment variables to be consumed by the initcontainers in the nifi registry helm chart and allows for customization of nifi registry images and tags.
No issue but I can create one if needed
This does not change the nifi registry version which remains at `0.8.0`
@banzo 
@AyadiAmen 
@alexnuttinck
=> Bump nifi registry version

.github/workflows/test.yml, Chart.yaml, values.yaml
https://kubernetes.io/docs/concepts/services-networking/service/
`LoadBalancer: Exposes the Service externally using a cloud provider's load balancer. NodePort and ClusterIP Services, to which the external load balancer routes, are automatically created.`
For example other helm charts use ClusterIP
- https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L313
- https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L102
- https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L111
- fixes #
=> Change serviceType to ClusterIP

.github/workflows/test.yml
Ports of port-forwarding changed 
in test.yaml file to support the new secured Nifi version.
=> Updating test.yml to support secured Nifi

templates/_helpers.tpl
Update registry host name to .Release.Name prefix
When helm install with custom name(ex. nifi-prod)
nifi-registry service name is nifi-prod-registry.
but nifi-registry host name is not nifi-prod-registry. 
(**actual**: http://nifi-registry:80, **predict** : http://nifi-prod-registry:80)
- fixes #
=> Update registry host name to .Release.Name prefix

Chart.yaml
see #180 
https://github.com/dysnix/charts/commit/dd9572a05742ccf0d4abef9d6f4ab886078ebf3f
=> bump nifi registry version to support new ingress version

Chart.yaml, README.md, templates/servicemonitor.yaml, values.yaml
Allow to create Service Monitor directly in the monitoring namespace
=> Add namespace to service monitor

.github/workflows/test.yml, Chart.yaml
Use latest version of nifi-registry chart (0.3.8)
- fixes #223
=> Bump Nifi registry version to 0.3.8

Chart.yaml, templates/statefulset.yaml
Signed-off-by: gforeman <gforeman@spinnerconsulting.com>
Fixes TLS settings issue and provides an alternate way to address spaces in the proxiedEntity value.
- fixes #237
I bumped the chart version to 1.0.7 assuming my other PR is approved.  I can adjust if the other PR is not desired or needs to be delayed.
=> correct tls source settings

configs/login-identity-providers-ldap.xml
The config file `login-identity-providers-ldap.xml`  has hard-coded values, see https://github.com/cetic/helm-nifi/issues/220
- fixes #220
=> Fix login-identity-providers-ldap hardcoded values

README.md, configs/bootstrap.conf, values.yaml
We need additional java options in bootstrap.conf to set up proxy for external internet access.
=> Add bootstrap options
