templates/statefulset.yaml

For use with custom nifi image and private repository

Add imagePullSecret to template

---

templates/statefulset.yaml

If nifi.web.http.host is the node hostname, the charts can support nifi cluster when replicas >1
In order to support nifi cluster when replicas>1.

modify nifi.web.http.host value to node hostname

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

Configure any nifi.properties line from values.yaml
Provides flexibility to set properties not already handled by this chart.  This can include using environment variables in values.yaml to accommodate nifi docker environment variables.
_Example_
```
properties:
safetyValve:
nifi.variable.registry.properties: ${NIFI_VARIABLE_REGISTRY_PROPERTIES}
some.new.property: "some new value"
```
- fixes #15
I didn't see a `./ci` directory to put test-values.yaml files.  Should I create them?
`prop_replace` method now takes a third argument for file name. I started to add the ability to change bootstrap.conf in a similar fashion as nifi.properties before realizing that the nifi user doesn't have permissions to write so it.  This can be explored later if needed.
[Place an '[x]' (no spaces) in all …

nifi.properties safety valve

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

@alexnuttinck 
Adds additional configuration possibilities for initContainers, extraVolumes and extraVolumeMounts which are then added to the pod-definition
- fixes #53

add initContainers, extraVolumes and extraVolumeMounts to values

---

README.md
templates/statefulset.yaml
values.yaml

This PR parameterizes the BusyBox image name.  When running NiFi on a cluster without Internet access, the image name may need to include a non-default repository.

Parameterize BusyBox image

---

templates/statefulset.yaml

If properties.isNode is false, then NiFi does not expect to connect to zookeeper and will never report itself as a ready cluster member.  So do not start the BusyBox initContainer to verify zookeeper connectivity, and do not wait for NiFi to report itself as a ready cluster member.

Only probe for zookeeper and cluster status if in cluster mode

---

README.md
templates/statefulset.yaml
values.yaml

This PR parameterizes the BusyBox and Alpine-tini image tags. This allows users to use immutable tags, which is strongly recommended in a production environment to avoid unexpected behavior upon pod rescheduling.

Parameterize zookeeper and log image tags

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

User can setup Statefulset Pod template annotations. One of the use case is special Prometheus annotation to let it to scrape the NiFi metrics from the Statefulset Pods.
- fixes #65 
@alexnuttinck

take statefulset pod annotations from Helm values

---

README.md
templates/statefulset.yaml
values.yaml

I suggest replacing the alpine-tiny docker image by busybox for the zookeeper connection check pod.
* ez123/alpine-tini has not been updated for almost 2 years.
* There is no need to pull an additional image like alpine-tiny given that busybox is already pulled and used for logging pods.

Replace alpine-tiny by busybox

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

Add Warning comment in the README.md

---

templates/statefulset.yaml
values.yaml

In the CA chart the `port` variable doesn't exist. `app_port` and `service.port` do. Since we will be wanting to point at the service with our helm nifi chart, we need to change the `ca.port` stuff to `ca.service.port`.
Here is the line in the ca chart: https://github.com/cetic/helm-nifi/blob/develop/charts/ca/values.yaml#L14
- fixes #

Fix ca port variable

---

README.md
configs/nifi.properties
values.yaml

This PR adds an option to specify a custom lib path for Nifi, for e.g. adding custom processors.
Nifi documentation on this feature: https://cwiki.apache.org/confluence/display/NIFI/2.+Before+You+Begin#id-2.BeforeYouBegin-customNARs
Signed-off-by: Sébastien Dupont <sebastien.dupont@cetic.be>

Add custom lib path configuration option

---

Chart.yaml
README.md
charts/ca/Chart.yaml
charts/ca/templates/_helpers.tpl
charts/ca/templates/deployment.yaml
charts/ca/templates/scc.yaml
charts/ca/templates/serviceaccount.yaml
charts/ca/values.yaml
templates/_helpers.tpl
templates/route.yaml
templates/scc.yaml
templates/serviceaccount.yaml
templates/statefulset.yaml
values.yaml

* Add Security Context Constraint support (SCC)
- Needed in order to run the Pods with arbitrary users in openshift
* Add Route support
- Routes replace Ingress in Openshift. While it is possible to use Ingress objects in Openshift, Routes offer support to some specific features
* Add ServiceAccount to satefulset
- SCC configurations require a target service account in order to set the correct secure context
- fixes #84 
The chart was tested on an Openshift 4.5 environment.

Add openshift support

---

Chart.yaml
configs/nifi.properties

Adding `nifi.nar.library.autoload.directory` the property to nifi.properties to allow autoreloading NAR files which allows the addition of custom processors without requiring a nifi restart. See [this page](https://www.nifi.rocks/auto-loading-extensions/) for more info.
None
None

Add nifi nar autoload directory property

---

Chart.yaml
configs/nifi.properties
templates/ingress.yaml
templates/statefulset.yaml

- The Ingress definition was using the httpPort by default instead of the httpsPort when the cluster was installed in secure mode.
-  Leave all the security configurations blank in nifi.properties by default.
- Set the keystore/truststore types to jks _only when clusterSecure is enabled_.
-  Corrected the label key for the soft antiAffinity configuration.
- fixes #77
- has some *partial* work towards #72 (this one still needs the ingress controller to know that the backend is using HTTPS instead of HTTP, I am not aware of any ingress-agnostic way to specify that)

Multiple fixes related to secure clusters

---

.github/workflows/stale.yml

Add scheduled job to mark issues as stale and close stale issues.
Ref: https://github.com/actions/stale
Current configuration: 
* dry-run mode
* only tags issues with `stale` label and add info message, does not close them
* except issues tagged with enhancement,bug,help wanted
* nothing on the PR

Stale issues triage

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

It adds support for setting your own affinity for NiFi.
Some people may want to set up their own nodeAffinities and all of the combinations of spec.affinity. The current chart doesn't allow for this. This PR adds the support to use your own Pod affinity provided you don't choose the default one (sts.AntiAffinity).
- fixes #122

Add affinity support for NiFi

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

It adds support for adding custom entries to the /etc/hosts file thanks to [spec.hostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/).

Add hostAliases support for NiFi

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

It adds imagePullPolicy support for NiFi sidecars. Sometimes, people do not want to pull the same images from the image registry. This PR adds the option to change it.

Add imagePullPolicy support for NiFi sidecars

---

.github/workflows/test.yml
README.md

Add basic Minikube test for the chart: deploys it, wait for the pods to be up and `curl` the web interface url. 
It is a first step towards automating testing for the chart (#91).

Basic test in Minikube

---

Chart.yaml
templates/statefulset.yaml

When you scale down the statefulset the offload process failed after the disconnecting call.
After disconnecting the node, further requests (check for DISCONNECTED state, offloading and deleting) are done on the node we have already disconnect and we got an error that we cannot request a disconnected node.
This PR fix that by getting the first active node and update baseUrl.

Fix offloading nodes

---

Chart.yaml
templates/statefulset.yaml

If OIDC is not enabled or clusterSecure is false, then safetyValve items do not get rendered into the statefulset YAML.  Apparently commit dbc0712785298c898d80dc4d10100cacec33a102 pulled in too much.
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

Re-enable safetyValve if OIDC is not enabled / clusterSecure false

---

Chart.yaml
values.yaml

Minor spelling mistake in the file

Fix spelling

---

Chart.yaml
README.md
configs/authorizers.xml
values.yaml

This adds the ability to configure the User and Group search scope for LDAP based authentication.
N/A

Feature: Make LDAP User/Group Search Scope Configurable

---

Chart.yaml
README.md
configs/authorizers.xml
doc/USERMANAGEMENT.md
values.yaml

Currently the LDAP bind dn gets used as the initial admin identity, when LDAP authentication is enabled. See #278 
- fixes #278

Fix LDAP bind dn forced as initial admin user

---

README.md
templates/statefulset.yaml
values.yaml

This PR is created because current chart functionality doesn't allow for modification or additions of Container Ports for the nifi pod. With this addition, we can now configure extra ports that can be listened on in order to utilize other functionality of Nifi in Kubernetes. For our use case, we need to actively manage additional ports because of some processors in NiFi where we can choose to listen on certain ports. Issue was that ports cannot be changed or added in Chart values. 
N/A

Allow addition of containerPort(s) to nifi via Helm Chart

---

doc/FAQ.md

Add session affinity FAQ

---

README.md
templates/statefulset.yaml
values.yaml

This PR adds the option of using one persistent volume instead of seven.  Some platforms have limits on the number of PVs per node and this option would make it easier for Nifi to be scheduled on a node.
- fixes #289
I removed the existingClaim references in the README as the value no longer exists.
I noted that the default for persistence is still false, whereas the helm recommendations list says it should be enabled by default.

feature/en289 Add a one-volume option for persistence using subPath

---

Chart.yaml
README.md
configs/nifi.properties
doc/INSTALLATION.md
templates/statefulset.yaml
tests/06-alpha.flow.xml
values.yaml

From NiFi 1.20.0 it supports configuration to enable/disable Zookeeper(zk) client zk Ensemble Tracker as of NIFI-10481.
With the zk ensemble tracker enabled (default by NiFi), NiFi zk client resolves the zk connection string to IP addresses then when all zk server pods get restarted and come up with a different IP, NiFi pods cannot reconnect to zk.
For NiFi from v1.17.0 to before v1.23.0, there is a TLS certificate auto-reload issue mentioned at [NIFI-11536](https://issues.apache.org/jira/browse/NIFI-11536).
- fixes #

Add zkClientEnsembleTracker configuration and upgrade NiFi to 1.23.2

---

templates/statefulset.yaml

This pull request allows `apache/nifi` versions `>=0.19.0` to be released with this helm chart.
As described in issue #313, this only required the keystore type to be explicitly set to `JKS` when calling `keytool` to be compatible with Java 11.
This change is backward compatible with Java 8. 
- fixes #313

Make compatible with apache/nifi >= 1.19.0 (#313)
